import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/libs/contexts/user.context";
import SuccessNotification from "@/components/SuccessNotification";
import ErrorNotification from "@/components/ErrorNotification";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SportMan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <SuccessNotification />
          <ErrorNotification />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
